name: adb_manager
description: "Adb device manager"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  collection: ^1.19.1
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  get_it: ^9.2.0
  uuid: ^4.5.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
